symfony/src/Entity/Structure.php
<?php

namespace App\Entity;

use App\Contract\LockableInterface;
use App\Tools\EscapedArray;
use DateInterval;
use DateTime;
use DateTimeInterface;
use DateTimeZone;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StructureRepository")
 * @ORM\Table(
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="pf_extid_idx", columns={"platform", "external_id"})
 *     },
 *     indexes={
 *         @ORM\Index(name="name_idx", columns={"name"})
 *     }
 * )
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 */
class Structure implements LockableInterface
{
    /**
     * @var int
     *
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=5)
     */
    private $platform;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank
     * @Assert\Length(max="64")
     */
    private $externalId;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank
     * @Assert\Length(max="64")
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=32, nullable=true)
     * @Assert\Length(max="32")
     */
    private $shortcut;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $enabled = true;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $locked = false;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max="255")
     */
    private $president;

    /**
     * @var Volunteer[]
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Volunteer", mappedBy="structures")
     */
    private $volunteers;

    /**
     * @var Structure|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Structure", inversedBy="childrenStructures")
     */
    private $parentStructure;

    /**
     * @var Structure[]
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Structure", mappedBy="parentStructure")
     */
    private $childrenStructures;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastPegassUpdate;

    /**
     * @var User[]
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="structures")
     */
    private $users;

    /**
     * @var PrefilledAnswers[]
     *
     * @ORM\OneToMany(targetEntity="App\Entity\PrefilledAnswers", mappedBy="structure")
     */
    private $prefilledAnswers;

    /**
     * @ORM\OneToMany(targetEntity=VolunteerList::class, mappedBy="structure", cascade={"all"}, orphanRemoval=true)
     */
    private $volunteerLists;

    /**
     * @ORM\OneToMany(targetEntity=Template::class, mappedBy="structure", orphanRemoval=true)
     */
    private $templates;

    public function __construct()
    {
        $this->volunteers         = new ArrayCollection();
        $this->childrenStructures = new ArrayCollection();
        $this->users              = new ArrayCollection();
        $this->prefilledAnswers   = new ArrayCollection();
        $this->volunteerLists     = new ArrayCollection();
        $this->templates          = new ArrayCollection();
    }

    public function getShortcut() : ?string
    {
        return $this->shortcut;
    }

    public function setShortcut(?string $shortcut) : Structure
    {
        $this->shortcut = $shortcut;

        return $this;
    }

    public function isLocked() : bool
    {
        return $this->locked;
    }

    public function setLocked(bool $locked) : Structure
    {
        $this->locked = $locked;

        return $this;
    }

    public function getDisplayName() : string
    {
        return mb_strtoupper($this->name);
    }

    public function getVolunteer(string $externalId) : ?Volunteer
    {
        foreach ($this->getVolunteers() as $volunteer) {
            if ($volunteer->getExternalId() === $externalId) {
                return $volunteer;
            }
        }

        return null;
    }

    /**
     * @return Collection|Volunteer[]
     */
    public function getVolunteers(bool $onlyEnabled = true) : Collection
    {
        if ($onlyEnabled) {
            return $this->getEnabledVolunteers();
        }

        return $this->volunteers->filter(function (Volunteer $volunteer) {
            return $this->platform === $volunteer->getPlatform();
        });
    }

    public function getExternalId() : string
    {
        return $this->externalId;
    }

    public function setExternalId(string $externalId) : Structure
    {
        $this->externalId = $externalId;

        return $this;
    }

    /**
     * @return Collection|Volunteer[]
     */
    public function getEnabledVolunteers() : Collection
    {
        return $this->volunteers->filter(function (Volunteer $volunteer) {
            return $this->platform === $volunteer->getPlatform() && $volunteer->isEnabled();
        });
    }

    public function getPlatform()
    {
        return $this->platform;
    }

    public function setPlatform($platform)
    {
        $this->platform = $platform;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function isEnabled() : bool
    {
        return $this->enabled;
    }

    /**
     * @param bool $enabled
     *
     * @return Structure
     */
    public function setEnabled(bool $enabled) : self
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * @param Volunteer $volunteer
     *
     * @return Structure
     */
    public function addVolunteer(Volunteer $volunteer) : self
    {
        if (!$this->volunteers->contains($volunteer)) {
            $this->volunteers[] = $volunteer;
            $volunteer->addStructure($this);
        }

        return $this;
    }

    /**
     * @param Volunteer $volunteer
     *
     * @return Structure
     */
    public function removeVolunteer(Volunteer $volunteer) : self
    {
        if ($this->volunteers->contains($volunteer)) {
            $this->volunteers->removeElement($volunteer);
            $volunteer->removeStructure($this);
        }

        return $this;
    }

    /**
     * @return Structure[]
     */
    public function getAncestors() : array
    {
        if (!$this->parentStructure) {
            return [];
        }

        return array_merge([$this->parentStructure], $this->parentStructure->getAncestors());
    }

    /**
     * @return Collection|self[]
     */
    public function getChildrenStructures() : Collection
    {
        return $this->childrenStructures;
    }

    /**
     * @param self $childrenStructure
     *
     * @return Structure
     */
    public function addChildrenStructure(self $childrenStructure) : self
    {
        if (!$this->childrenStructures->contains($childrenStructure)) {
            $this->childrenStructures[] = $childrenStructure;
            $childrenStructure->setParentStructure($this);
        }

        return $this;
    }

    /**
     * @param self $childrenStructure
     *
     * @return Structure
     */
    public function removeChildrenStructure(self $childrenStructure) : self
    {
        if ($this->childrenStructures->contains($childrenStructure)) {
            $this->childrenStructures->removeElement($childrenStructure);
            // set the owning side to null (unless already changed)
            if ($childrenStructure->getParentStructure() === $this) {
                $childrenStructure->setParentStructure(null);
            }
        }

        return $this;
    }

    /**
     * @return Structure|null
     */
    public function getParentStructure() : ?self
    {
        return $this->parentStructure;
    }

    /**
     * @param self|null $parentStructure
     *
     * @return Structure
     */
    public function setParentStructure(?self $parentStructure) : self
    {
        $this->parentStructure = $parentStructure;

        return $this;
    }

    public function hasChildren() : bool
    {
        return (bool) $this->childrenStructures->count();
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getLastPegassUpdate() : ?DateTimeInterface
    {
        return $this->lastPegassUpdate;
    }

    /**
     * @param DateTimeInterface|null $lastPegassUpdate
     *
     * @return Structure
     */
    public function setLastPegassUpdate(?DateTimeInterface $lastPegassUpdate) : self
    {
        $this->lastPegassUpdate = $lastPegassUpdate;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers() : Collection
    {
        return $this->users->filter(function (User $user) {
            return $this->platform === $user->getPlatform();
        });
    }

    public function addUser(User $user) : self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addStructure($this);
        }

        return $this;
    }

    public function removeUser(User $user) : self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeStructure($this);
        }

        return $this;
    }

    /**
     * @return Collection|PrefilledAnswers[]
     */
    public function getPrefilledAnswers() : Collection
    {
        return $this->prefilledAnswers;
    }

    public function addPrefilledAnswer(PrefilledAnswers $prefilledAnswer) : self
    {
        if (!$this->prefilledAnswers->contains($prefilledAnswer)) {
            $this->prefilledAnswers->add($prefilledAnswer);
            $prefilledAnswer->setStructure($this);

symfony/src/Form/Type/StructureType.php
<?php

namespace App\Form\Type;

use App\Entity\Structure;
use App\Manager\StructureManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StructureType extends AbstractType
{
    /**
     * @var StructureManager
     */
    private $structureManager;

    public function __construct(StructureManager $structureManager)
    {
        $this->structureManager = $structureManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'structure.form.name',
            ])
            ->add('shortcut', TextType::class, [
                'required' => false,
                'label'    => 'structure.form.shortcut',
            ])
            ->add('parentStructure', StructureWidgetType::class, [
                'required' => false,
                'label'    => 'structure.form.parent',
            ])
            ->add('president', VolunteerWidgetType::class, [
                'required' => false,
                'label'    => 'structure.form.president',
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'base.button.submit',
            ]);

        $builder->get('parentStructure')->addModelTransformer(new CallbackTransformer(
            function (?Structure $fromBase) {
                return $fromBase ? $fromBase->getId() : null;
            },
            function ($fromForm) {
                return $fromForm ? $this->structureManager->find($fromForm) : null;
            }
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class' => Structure::class]);
    }
}

symfony/src/Controller/Management/HomeController.php
<?php

namespace App\Controller\Management;

use App\Base\BaseController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route(path="management/", name="management_")
 */
class HomeController extends BaseController
{
    /**
     * @Route(name="home")
     */
    public function indexAction()
    {
        return $this->render('management/home.html.twig', [
            'email' => getenv('MINUTIS_SUPPORT'),
        ]);
    }
}

symfony/src/Controller/Management/IssuesController.php
<?php

namespace App\Controller\Management;

use App\Base\BaseController;
use App\Manager\VolunteerManager;
use App\Tools\PhoneNumberParser;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @Route(path="management/issues", name="management_issues_")
 */
class IssuesController extends BaseController
{
    /**
     * @var VolunteerManager
     */
    private $volunteerManager;

    /**
     * @var ValidatorInterface
     */
    private $validator;

    /**
     * @param VolunteerManager   $volunteerManager
     * @param ValidatorInterface $validator
     */
    public function __construct(VolunteerManager $volunteerManager, ValidatorInterface $validator)
    {
        $this->volunteerManager = $volunteerManager;
        $this->validator        = $validator;
    }

    /**
     * @Route(path="/", name="index")
     */
    public function index()
    {
        return $this->render('issues/index.html.twig', [
            'issues' => $this->volunteerManager->getIssues(),
            'gaia'   => getenv('GAIA_URL'),
        ]);
    }
}

symfony/src/Controller/Management/Structure/PrefilledAnswersController.php
<?php

namespace App\Controller\Management\Structure;

use App\Base\BaseController;
use App\Entity\PrefilledAnswers;
use App\Entity\Structure;
use App\Form\Type\PrefilledAnswersType;
use App\Manager\PrefilledAnswersManager;
use Bundles\PaginationBundle\Manager\PaginationManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route(path="management/structures/{structure}/prefilled-answers", name="management_structures_prefilled_answers_")
 * @ParamConverter("structure", options={"id" = "structure"})
 * @Security("is_granted('STRUCTURE', structure)")
 */
class PrefilledAnswersController extends BaseController
{
    /**
     * @var PaginationManager
     */
    private $paginationManager;

    /**
     * @var PrefilledAnswersManager
     */
    private $prefilledAnswersManager;

    public function __construct(PaginationManager $paginationManager, PrefilledAnswersManager $prefilledAnswersManager)
    {
        $this->paginationManager       = $paginationManager;
        $this->prefilledAnswersManager = $prefilledAnswersManager;
    }

    /**
     * @Route("/", name="list")
     * @Template("management/structures/prefilled_answers/list.html.twig")
     */
    public function listPrefilledAnswers(Structure $structure)
    {
        $prefilledAnswers = $this->prefilledAnswersManager->getPrefilledAnswersByStructure($structure);

        return ['pager' => $this->paginationManager->getPager($prefilledAnswers), 'structure' => $structure];
    }

    /**
     * @Route("/{prefilledAnswers}/editor", requirements={"prefilledAnswers" = "\d+"}, name="edit")
     * @Route("/new", name="new")
     * @Template("management/structures/prefilled_answers/editor.html.twig")
     */
    public function editorPrefilledAnswers(Request $request, Structure $structure)
    {
        if ($request->get('prefilledAnswers') === null) {
            $prefilledAnswers = new PrefilledAnswers();
            $prefilledAnswers->setPlatform($this->getPlatform());
            $prefilledAnswers->setStructure($structure);
        } else {
            $prefilledAnswers = $this->prefilledAnswersManager->findById($request->get('prefilledAnswers'));
            if (!$prefilledAnswers) {
                throw $this->createNotFoundException();
            }
        }

        $form = $this
            ->createForm(PrefilledAnswersType::class, $prefilledAnswers)
            ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->prefilledAnswersManager->save($prefilledAnswers);

            return $this->redirectToRoute('management_structures_prefilled_answers_list', ['structure' => $structure->getId()]);
        }

        return ['form' => $form->createView(), 'structure' => $structure];
    }

    /**
     * @Route("/{prefilledAnswers}/delete", requirements={"prefilledAnswers" = "\d+"}, name="delete")
     */
    public function deleteAction(Request $request, PrefilledAnswers $prefilledAnswers, Structure $structure)
    {
        $this->validateCsrfOrThrowNotFoundException('prefilled_answers', $request->get('csrf'));

        $this->prefilledAnswersManager->remove($prefilledAnswers);

        return $this->redirectToRoute('management_structures_prefilled_answers_list', ['structure' => $structure->getId()]);
    }
}

symfony/templates/management/structures/form.html.twig
{% extends 'base.html.twig' %}

{% import 'macros.html.twig' as macros %}

{% block body %}

    <h1>
        {% if structure.id %}
            {{ 'manage_structures.form.update'|trans({'%name%': structure.displayName}) }}
        {% else %}
            {{ 'manage_structures.form.create'|trans }}
        {% endif %}
    </h1>

    {{ form(form) }}

    <br/>

    <div class="text-center">
        <a href="{{ path('management_structures_list') }}"
           class="btn btn-secondary">{{ 'base.button.back'|trans }}</a>
    </div>

    <br/><br/>

{% endblock %}

symfony/templates/management/structures/list.html.twig
{% extends 'base.html.twig' %}

{% import 'macros.html.twig' as macros %}

{% block body %}

    <h1>
        {{ 'manage_structures.title'|trans }}
    </h1>

    <div class="text-right">
        {% if is_granted('ROLE_ADMIN') %}
            <a href="{{ path('management_structures_create') }}" class="btn btn-secondary">
                {{ 'manage_structures.form.create'|trans }}
            </a>
        {% endif %}
    </div>

    {{ form(search) }}

    <div class="row">
        {% for structure in structures %}
            <div class="col-6" id="structure-{{ structure.id }}" style="padding:5px;">
                {{ include('management/structures/structure.html.twig', {structure: structure}) }}
            </div>
        {% endfor %}
    </div>

    {{ macros.pager(structures) }}

    <div>{{ 'lock.explanation'|trans }}</div>
    <br/>

    <div class="text-center">
        <a href="{{ path('management_home') }}" class="btn btn-secondary">{{ 'base.button.back'|trans }}</a>
    </div>

    <br/><br/>

    <div class="modal fade" id="redcall-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 id="redcall-user-modal-title" class="modal-title"></h5>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="form-check">
                    <label class="switch">
                        <input type="checkbox"
                               data-toggle="toggle" data-onstyle="primary"
                               class="form-check-input"
                               id="includes-children"/>
                        <span class="slider"></span>
                    </label>
                    <label class="form-check-label"
                           for="includes-children">
                        {{ 'manage_structures.include_children'|trans }}
                    </label>
                </div>

                <div id="redcall-user-modal-body" class="modal-body text-center"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ 'base.modal.close'|trans }}</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script type="text/javascript">

        $('body').on('click', '.toggle-action', function (e) {
            e.preventDefault();
            var that = $(this);

            if (!that.data('confirm') || confirm(that.data('confirm'))) {
                $.post(that.data('href'), function (data) {
                    $('#structure-' + that.data('id')).html(data);
                });
            }
        });

        $('body').on('click', '.show-structure-users', function (e) {
            e.preventDefault();
            $('#redcall-user-modal-title').html('');
            $('#redcall-user-modal-body').html('<img src="{{ asset('spinner.gif') }}"/>');
            $('#redcall-user-modal').modal();
            $.post('{{ path('management_structures_list_users') }}', {
                id: $(this).data('structure-id'),
                include_children: $('#includes-children').is(':checked') ? 1 : 0
            }, function (data) {
                $('#redcall-user-modal-title').html(data.title);
                $('#redcall-user-modal-body').html(data.body);
            });
        });

        $('body').on('change', '#includes-children', function () {
            if ($('#redcall-user-modal').is(':visible')) {
                $('.show-structure-users').trigger('click');
            }
        });

    </script>

{% endblock %}

symfony/templates/management/structures/pegass.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>{{ structure.name }}</h1>
    <h3 class="color-grey">{{ entity.updatedAt|date('d/m/Y H:i') }}</h3>

    <div class="jumbotron shadow p-3 mb-5 rounded">
        <pre><code>{{ pegass|nl2br }}</code></pre>
    </div>

{% endblock %}

symfony/templates/management/structures/structure.html.twig
<div class="card shadow">
    <div class="card-header">
        <div class="card-title">
            <a href="{{ path('management_volunteers_list', {id: structure.id}) }}">
                <strong style="{% if not structure.enabled %}color:grey;{% endif %}">{{ structure.name }}</strong>
            </a>
            {% if not structure.enabled %}🚫{% endif %}
            <div class="float-right">
                <div class="dropdown">
                    <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ 'manage_structures.action.title'|trans }}
                    </button>

                    <div class="dropdown-menu dropdown-menu-right">
                        {% if structure.enabled %}

{#                            {% if not structure.locked and constant('\\App\\Enum\\Platform::FR') == app.user.platform and structure.lastPegassUpdate %}#}
{#                                {% if is_granted('ROLE_ADMIN') %}#}
{#                                    <a class="dropdown-item" href="{{ path('management_structures_pegass', {id: structure.id}) }}" target="_blank">#}
{#                                        {{ 'manage_structures.view_pegass_entry'|trans }}#}
{#                                    </a>#}
{#                                {% endif %}#}
{#                            {% endif %}#}
                            {% if is_granted('ROLE_ADMIN') %}
                                <a class="dropdown-item" href="{{ path('management_structures_create', {id: structure.id}) }}">
                                    {{ 'manage_structures.manual_update'|trans }}
                                </a>
                                <div class="dropdown-divider"></div>
                            {% endif %}

                            <a class="dropdown-item" href="{{ path('management_structures_export', {id: structure.id} ) }}">
                                {{ 'manage_structures.export'|trans }}
                            </a>

                            <a class="dropdown-item" href="{{ path('management_structures_template_list', {structure: structure.id}) }}">
                                {{ 'manage_structures.templates.menu'| trans }}
                            </a>

                            <a class="dropdown-item" href="{{ path('management_structures_prefilled_answers_list', {structure: structure.id}) }}">
                                {{ 'manage_structures.manage_prefilled_answers'| trans }}
                            </a>

                            <a class="dropdown-item" href="{{ path('management_structures_volunteer_lists_index', {structureId: structure.id}) }}">
                                {{ 'manage_structures.manage_volunteer_lists'| trans }}
                            </a>
                        {% endif %}

                        {% if app.user.root %}

                            <div class="dropdown-divider"></div>

                            <div class="dropdown-header">{{ 'admin.resources.change_platform_title'|trans }}</div>
                            {% for platform in platforms %}
                                <a class="dropdown-item {% if platform == structure.platform %}disabled{% else %}text-primary{% endif %}" href="{{ path('management_structures_update_platform', {id: structure.id, csrf: csrf_token('csrf'), platform: platform}) }}" {% if platform == structure.platform %}onclick="return false;"{% endif %}>
                                    {{ 'admin.resources.change_platform'|trans({'%platform%': platform.flag ~ ' ' ~ platform.label}) }}
                                </a>
                            {% endfor %}

                        {% endif %}

                        {% if is_granted('ROLE_ADMIN') %}

                            {% if structure.enabled %}
                                <div class="dropdown-divider"></div>
                            {% endif %}

                            {% if structure.enabled %}
                                <a href="#"
                                   class="dropdown-item text-danger toggle-action"
                                   data-href="{{ path('management_structures_toggle_enable', {id: structure.id, token: csrf_token('token')}) }}"
                                   data-id="{{ structure.id }}"
                                   data-confirm="{{ 'manage_structures.disable_confirm'|trans }}">
                                    {{ 'base.button.disable'| trans }}
                                </a>
                            {% else %}
                                <a href="#"
                                   class="dropdown-item text-success toggle-action"
                                   data-href="{{ path('management_structures_toggle_enable', {id: structure.id, token: csrf_token('token')}) }}"
                                   data-id="{{ structure.id }}">
                                    {{ 'base.button.enable'| trans }}
                                </a>
                            {% endif %}

                        {% endif %}
                    </div>
                </div>
            </div>
            {% if structure.shortcut %}
                <div>{{ structure.shortcut }}</div>
            {% endif %}
        </div>
    </div>
    <div class="card-body">

        <span style="{% if not structure.enabled %}color:grey;{% endif %}">
            {% set president = structure.presidentVolunteer %}
            {% if president %}
                {{ 'manage_structures.president'|trans({'%president%': president.displayName}) }}
                <br/>
            {% endif %}

            {{ 'manage_structures.volunteers'|trans({'%count%': structure.volunteers|length}) }}
            <br/>

            {{ 'manage_structures.users'|trans({'%count%': redcallUsers[structure.id]|default(0)}) }}
            {% if redcallUsers[structure.id]|default(0) %}
                (<a href="#"
                    class="show-structure-users"
                    data-structure-id="{{ structure.id }}">{{ 'base.button.details'|trans }}</a>)
            {% endif %}

            {% if constant('\\App\\Enum\\Platform::FR') == app.user.platform %}
                {% if structure.lastPegassUpdate %}
                    <br/>
                    {{ 'manage_structures.last_update'|trans({'%last_update%': structure.lastPegassUpdate|date('d/m/Y H:i')}) }}
                {% endif %}

                {% if structure.nextPegassUpdate %}
                <br/>
                {{ 'manage_structures.next_update'|trans({'%next_update%': structure.nextPegassUpdate|date('d/m/Y H:i')}) }}
            {% endif %}

            {% endif %}
        </span>

    </div>
    <div class="card-footer">
        {% if is_granted('ROLE_ADMIN') %}
            {% if structure.locked %}
                <a href="#"
                   class="toggle-action"
                   style="text-decoration: none;"
                   data-id="{{ structure.id }}"
                   data-href="{{ path('management_structures_toggle_lock', {id: structure.id, token: csrf_token('token')}) }}" title="{{ 'manage_structures.unlock'|trans }}">
                    🔒
                    <span style="color:grey;">{{ 'lock.locked'|trans }}</span>
                </a>
            {% else %}
                <a href="#"
                   class="toggle-action"
                   style="text-decoration: none;"
                   data-id="{{ structure.id }}"
                   data-href="{{ path('management_structures_toggle_lock', {id: structure.id, token: csrf_token('token')}) }}" title="{{ 'manage_structures.lock'|trans }}">🔓</a>
            {% endif %}
        {% endif %}

        <div class="float-right">
            <span style="color:lightgray;">ID: <a href="#" style="color:lightgray;" class="copy-to-clipboard">{{ structure.externalId }}</a></span>
        </div>
    </div>
</div>

symfony/templates/management/structures/users.html.twig
{% import 'macros.html.twig' as macros %}

<div class="row text-left">
    {% for user in users %}
        {% if user.volunteer %}
            <div class="col-md-6" style="padding:5px;">
                {{ macros.volunteer(user.volunteer) }}
                <hr/>
            </div>
        {% endif %}
    {% endfor %}
</div>