symfony/src/Entity/Volunteer.php
<?php

namespace App\Entity;

use App\Contract\LockableInterface;
use App\Tools\EscapedArray;
use DateInterval;
use DateTime;
use DateTimeZone;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Table(
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="pf_extid_idx", columns={"platform", "external_id"})
 *     },
 *     indexes={
 *         @ORM\Index(name="emailx", columns={"email"}),
 *         @ORM\Index(name="internal_emailx", columns={"internal_email"}),
 *         @ORM\Index(name="enabledx", columns={"enabled"}),
 *         @ORM\Index(name="phone_number_optinx", columns={"phone_number_optin"}),
 *         @ORM\Index(name="email_optinx", columns={"email_optin"}),
 *         @ORM\Index(name="optout_untilx", columns={"optout_until"})
 *     }
 * )
 * @ORM\Entity(repositoryClass="App\Repository\VolunteerRepository")
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 */
class Volunteer implements LockableInterface
{
    /**
     * @var int
     *
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $platform;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank
     * @Assert\Length(max="64")
     */
    private $externalId;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=80, nullable=true)
     * @Assert\NotBlank
     * @Assert\Length(max=80)
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=80, nullable=true)
     * @Assert\NotBlank
     * @Assert\Length(max=80)
     */
    private $lastName;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=80, nullable=true)
     * @Assert\Length(max=80)
     * @Assert\Email
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=80, nullable=true)
     * @Assert\Length(max=80)
     * @Assert\Email
     */
    private $internalEmail;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" : 1})
     */
    private $enabled = true;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $locked = false;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $minor = false;

    /**
     * @var \DateTimeInterface
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastPegassUpdate;

    /**
     * @var array
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $report;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Structure", inversedBy="volunteers")
     */
    private $structures;

    /**
     * @var User
     *
     * @ORM\OneToOne(targetEntity="App\Entity\User", mappedBy="volunteer")
     */
    private $user;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $phoneNumberLocked = false;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $emailLocked = false;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" : 1})
     */
    private $phoneNumberOptin = true;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" : 1})
     */
    private $emailOptin = true;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="volunteer", cascade={"persist"})
     * @ORM\OrderBy({"communication" = "DESC"})
     */
    private $messages;

    /**
     * @ORM\ManyToMany(targetEntity=Phone::class, mappedBy="volunteers", orphanRemoval=true, cascade={"all"})
     * @ORM\OrderBy({"preferred" = "DESC"})
     *
     * @Assert\Valid
     */
    private $phones;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $onlyOutboundSms = false;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" : 1})
     */
    private $supportsShortCode = true;

    /**
     * @ORM\ManyToMany(targetEntity=Badge::class, inversedBy="volunteers")
     */
    private $badges;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $optoutUntil;

    /**
     * @ORM\ManyToMany(targetEntity=VolunteerList::class, mappedBy="volunteers")
     */
    private $lists;

    public function __construct()
    {
        $this->structures = new ArrayCollection();
        $this->messages   = new ArrayCollection();
        $this->phones     = new ArrayCollection();
        $this->badges     = new ArrayCollection();
        $this->lists      = new ArrayCollection();
    }

    public function getFullname() : string
    {
        return $this->firstName.' '.$this->lastName;;
    }

    public function getPhoneNumber() : ?string
    {
        $phone = $this->getPhone();

        return $phone ? $phone->getE164() : null;
    }

    public function getPhone() : ?Phone
    {
        foreach ($this->getPhones() as $phone) {
            if ($phone->isPreferred()) {
                return $phone;
            }
        }

        return null;
    }

    /**
     * @return Phone[]
     */
    public function getPhones() : Collection
    {
        return $this->phones;
    }

    public function getPhoneByNumber(string $e164) : ?Phone
    {
        foreach ($this->getPhones() as $phone) {
            if ($phone->getE164() === $e164) {
                return $phone;
            }
        }

        return null;
    }

    public function hasPhoneNumber(string $phoneNumber) : bool
    {
        foreach ($this->phones as $phone) {
            /** @var Phone $phone */
            if ($phoneNumber === $phone->getE164()) {
                return true;
            }
        }

        return false;
    }

    public function getEmail() : ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email) : Volunteer
    {
        $this->email = $email;

        return $this;
    }

    public function getInternalEmail() : ?string
    {
        return $this->internalEmail;
    }

    public function setInternalEmail(?string $internalEmail) : Volunteer
    {
        $this->internalEmail = $internalEmail;

        return $this;
    }

    public function isLocked() : ?bool
    {
        return $this->locked;
    }

    public function setLocked(bool $locked) : Volunteer
    {
        $this->locked = $locked;

        return $this;
    }

    public function getDisplayName() : string
    {
        if ($this->firstName && $this->lastName) {
            return sprintf('%s %s', $this->toName($this->firstName), $this->toName($this->lastName));
        }

        return sprintf('#%s', mb_strtoupper($this->externalId));
    }

    public function isMinor() : bool
    {
        return $this->minor;
    }

    public function setMinor(bool $minor) : void
    {
        $this->minor = $minor;
    }

    public function getFormattedPhoneNumber() : ?string
    {
        return $this->getPhone() ? $this->getPhone()->getNational() : null;
    }

    public function getLastPegassUpdate() : ?\DateTimeInterface
    {
        return $this->lastPegassUpdate;
    }

    public function setLastPegassUpdate(\DateTimeInterface $lastPegassUpdate) : Volunteer
    {
        $this->lastPegassUpdate = $lastPegassUpdate;

        return $this;
    }

    public function isCallable() : bool
    {
        $hasPhone = $this->getPhone() && $this->phoneNumberOptin;
        $hasEmail = $this->email && $this->emailOptin;
        $isOptin  = !$this->optoutUntil || $this->optoutUntil->getTimestamp() < time();

        return $this->enabled && $isOptin && ($hasPhone || $hasEmail);
    }

    public function addReport(string $message)
    {
        $report   = $this->getReport() ?? [];
        $report[] = $message;
        $this->setReport($report);
    }

    public function getReport() : ?array
    {
        return $this->report ? json_decode($this->report, true) : null;
    }

    public function setReport(array $report) : Volunteer
    {
        $this->report = json_encode($report, JSON_PRETTY_PRINT);

        return $this;
    }

    public function getStructureIds() : array
    {
        return array_map(function (Structure $structure) {
            return $structure->getId();
        }, $this->getStructures()->toArray());
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     *
     * @return $this
     */
    public function setId(int $id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return Structure[]
     */
    public function getStructures(bool $onlyEnabled = true) : Collection
    {
        if ($onlyEnabled) {
            return $this->getEnabledStructures();
        }

        return $this->structures->filter(function (Structure $structure) {
            return $this->platform === $structure->getPlatform();
        });
    }

    public function getEnabledStructures() : Collection
    {
        return $this->structures->filter(function (Structure $structure) {
            return $this->platform === $structure->getPlatform() && $structure->isEnabled();
        });
    }

    public function getPlatform()
    {
        return $this->platform;
    }

    public function setPlatform($platform)
    {
        $this->platform = $platform;

        return $this;
    }

    public function isEnabled() : ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled) : Volunteer
    {
        $this->enabled = $enabled;

        return $this;
    }

symfony/templates/space/consult_data.html.twig
{% extends 'base.html.twig' %}

{% block menu %}{% endblock %}

{% block body %}

    <br/>

    <div class="jumbotron shadow p-3 mb-5 rounded">

        <div class="text-right">
            <a href="{{ path('space_download_data', {sessionId: session.sessionId}) }}">{{ 'space.consult_data.download_btn'|trans }}</a>
        </div>

        {{ include('space/data.html.twig') }}

    </div>

    <a href="{{ path('space_home', {sessionId: session.sessionId}) }}"
       class="btn btn-secondary">{{ 'base.button.back'|trans }}</a>

    <br/><br/>

{% endblock %}

symfony/templates/space/delete_data.html.twig
{% extends 'base.html.twig' %}

{% block menu %}{% endblock %}

{% block body %}

    <br/>

    <div class="jumbotron shadow p-3 mb-5 rounded">

        <h3>{{ 'space.delete_data.title'|trans }}</h3>

        <hr/>

        <p>{{ 'space.delete_data.detail_1'|trans }}</p>
        <br/>
        <p>{{ 'space.delete_data.detail_2'|trans }}</p>
        <br/>
        <p>{{ 'space.delete_data.detail_3'|trans }}</p>

        <br/>

        <div id="delete-buttons" class="d-none">
            {{ form(form) }}
        </div>

        <a href="#" class="btn btn-primary" id="ask-deletion">{{ 'space.delete_data.delete_button'|trans }}</a>

    </div>

    <a href="{{ path('space_home', {sessionId: session.sessionId}) }}"
       class="btn btn-secondary">{{ 'base.button.back'|trans }}</a>

    <br/><br/>

    <script type="text/javascript">

        $('#ask-deletion').click(function (e) {
            e.preventDefault();
            $(this).addClass('d-none');
            $('#delete-buttons').removeClass('d-none');
        });

        $('#{{ form.cancel.vars.id }}').click(function (e) {
            e.preventDefault();
            $('#ask-deletion').removeClass('d-none');
            $('#delete-buttons').addClass('d-none');
        });

    </script>

{% endblock %}

symfony/templates/space/email.html.twig
{% extends 'base.html.twig' %}

{% block menu %}{% endblock %}

{% block body %}

    <br/>
    <div class="jumbotron shadow p-3 mb-5 rounded">

        <div class="h3">{{ 'space.email.title'|trans }}</div>

        <p>{{ 'space.email.details_1'|trans }}</p>
        <br/>

        {{ form(form) }}

        <p>{{ 'space.email.details_2'|trans({'%from%': from}) }}</p>
        <br/>
        <p>{{ 'space.email.details_3'|trans }} {{ 'space.email.details_4'|trans }} </p>

    </div>

    <a href="{{ path('space_home', {sessionId: session.sessionId}) }}"
       class="btn btn-secondary">{{ 'base.button.back'|trans }}</a>

    <br/><br/>

{% endblock %}

symfony/templates/space/enabled.html.twig
{% extends 'base.html.twig' %}

{% block menu %}{% endblock %}

{% block body %}

    <br/>
    <div class="jumbotron shadow p-3 mb-5 rounded">

        <div class="h3">{{ 'space.enabled.title'|trans }}</div>

        <p>{{ 'space.enabled.details_1'|trans }}</p>

        <br/>

        {{ form(form) }}

        <br/>

        <p>{{ 'space.enabled.details_2'|trans }}</p>

    </div>

    <a href="{{ path('space_home', {sessionId: session.sessionId}) }}"
       class="btn btn-secondary">{{ 'base.button.back'|trans }}</a>

    <br/><br/>

{% endblock %}

symfony/templates/space/index.html.twig
{% extends 'base.html.twig' %}

{% import 'macros.html.twig' as macros %}

{% block menu %}{% endblock %}

{% block body %}
    <br/>

    <div class="jumbotron shadow p-3 mb-5 rounded text-center">

        <div>
            <img src="{{ asset('apple-touch-icon.png') }}" style="max-height: 50px;"/>
        </div>

        <br/>

        {% if session.volunteer.user %}

            <div class="alert alert-info">
                <p>💡</p>
                <div>{{ 'space.home.user_title'|trans }}</div>
                <p>{{ 'space.home.user_details'|trans }}</p>
            </div>

        {% else %}

            <a href="{{ path('space_infos', {sessionId: session.sessionId}) }}"
               class="text-lg-center large-button btn btn-secondary">{{ 'space.infos.title'|trans }}</a>

            <br/>

        {% endif %}

        <hr/>

        <div class="h4 text-left">{{ 'space.home.contact'|trans }}</div>
        <br/>

        <a href="{{ path('space_phone', {sessionId: session.sessionId}) }}"
           class="text-lg-left large-button btn btn-secondary">
            {% if session.volunteer.phone %}
                ☎️ &nbsp; {{ 'space.home.update_phone'|trans }}
                <span style="color:black;">{{ session.volunteer.hiddenPhone }}</span>
            {% else %}
                ☎️ &nbsp; {{ 'space.home.add_phone'|trans }}
            {% endif %}
        </a>

        <br/><br/>

        <a href="{{ path('space_email', {sessionId: session.sessionId}) }}"
           class="text-lg-left large-button btn btn-secondary">
            {% if session.volunteer.email %}
                📧 &nbsp; {{ 'space.home.update_email'|trans }}
                <span style="color:black">{{ session.volunteer.hiddenEmail }}</span>
            {% else %}
                📧 &nbsp; {{ 'space.home.add_email'|trans }}
            {% endif %}
        </a>

        <br/><br/>

        <a href="{{ path('space_enabled', {sessionId: session.sessionId}) }}"
           class="text-lg-left large-button btn btn-secondary">
            {% if session.volunteer.callable %}
                ❤️ &nbsp; {{ 'space.home.toggle_callable'|trans }}
                <span style="color:green;">{{ 'space.home.callable'|trans }}</span>)
            {% else %}
                ❤️ &nbsp; {{ 'space.home.toggle_callable'|trans }}
                <span style="color:red;">{{ 'space.home.not_callable'|trans }}</span>)
            {% endif %}
        </a>

        <br/>
        <hr/>

        {% if messages %}

            <div class="h4 text-left">{{ 'space.home.triggers.title'|trans }}</div>

            <br/>

            <div class="text-left">
                <table class="table table-striped">
                    <tbody>
                    {% for message in messages %}
                        <tr>
                            <td>
                                {{ macros.communicationIcon(message.communication) }}
                                {{ 'space.home.triggers.subject'|trans({
                                    '%type%': '<strong>' ~ ('space.home.triggers.' ~ message.communication.type)|trans ~ '</strong>',
                                    '%date%': message.communication.createdAt|date('d/m/Y'),
                                    '%time%': message.communication.createdAt|date('H:i')
                                })|raw }}
                            </td>
                            <td>
                                <a href="{{ path('message_open', {code: message.code}) }}" target="_blank" class="btn btn-primary">
                                    {{ 'base.button.open'|trans }}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <hr/>

        {% endif %}

        <div class="h4 text-left">{{ 'space.home.data'|trans }}</div>

        <br/>

        <a href="{{ path('space_consult_data', {sessionId: session.sessionId}) }}"
           class="text-lg-left large-button btn btn-secondary">
            💾 &nbsp; {{ 'space.home.data_access'|trans }}
        </a>

        <br/><br/>

        <a href="{{ path('space_delete_data', {sessionId: session.sessionId}) }}"
           class="text-lg-left large-button btn btn-secondary">
            🔥 &nbsp; {{ 'space.home.data_delete'|trans }}
        </a>

        <br/><br/>

        <div class="text-left">
            <p>🍪 &nbsp; {{ 'space.home.no_tracking'|trans }}</p>
        </div>

        <hr/>

        <a href="{{ path('space_logout', {sessionId: session.sessionId}) }}"
           class="text-lg-center large-button btn btn-secondary">{{ 'space.logout'|trans }}</a>

    </div>

{% endblock %}

symfony/templates/space/infos.html.twig
{% extends 'base.html.twig' %}

{% block menu %}{% endblock %}

{% block body %}

    <br/>
    <div class="row jumbotron shadow p-3 mb-5 rounded">

        <div class="col-md-12">
            <p>{{ 'space.infos.context_1'|trans }}</p>
            <br/>
            <ul>
                <li>
                    <p>{{ 'space.infos.context_2'|trans }}</p>
                    <br/>
                </li>
                <li>
                    <p>{{ 'space.infos.context_3'|trans }}</p>
                </li>
            </ul>

            <p>{{ 'space.infos.context_4'|trans }} {{ 'space.infos.context_5'|trans }}</p>
        </div>

        <div class="col-md-6">
            <br/>
            <p>{{ 'space.infos.context_6'|trans }}</p>
            <img class="img-fluid" src="{{ asset('message.png') }}"/>
        </div>
        <div class="col-md-6">
            <br/>
            <p>{{ 'space.infos.context_7'|trans }}</p>
            <img class="img-fluid" src="{{ asset('reponses.png') }}"/>
        </div>

        <div class="col-md-12">
            <br/>
            <p>{{ 'space.infos.context_8'|trans }}</p>
            <br/>
            <p>{{ 'space.infos.context_9'|trans }}</p>
            <p>{{ 'space.infos.context_10'|trans }}</p>
            <p>{{ 'space.infos.context_11'|trans }}</p>
            <p>{{ 'space.infos.context_12'|trans }}</p>
            <p>{{ 'space.infos.context_13'|trans }}</p>
        </div>

    </div>

    <a href="{{ path('space_home', {sessionId: session.sessionId}) }}"
       class="btn btn-secondary">{{ 'base.button.back'|trans }}</a>

    <br/><br/>

{% endblock %}

symfony/templates/space/phone.html.twig
{% extends 'base.html.twig' %}

{% block menu %}{% endblock %}

{% block body %}

    <br/>
    <div class="jumbotron shadow p-3 mb-5 rounded">

        <div class="h3">{{ 'space.phone.title'|trans }}</div>

        <p>{{ 'space.phone.details_1'|trans }}</p>
        <br/>

        {{ form(form) }}

        {% if country %}
            {% if country.outboundSmsEnabled %}
                <p>
                    {{ 'space.phone.details_6'|trans }}
                    {% if country.outboundSmsShort %}
                        {{ country.outboundSmsShort }}
                    {% endif %}
                    {% if country.outboundSmsShort and country.outboundSmsLong %}
                        /
                    {% endif %}
                    {% if country.outboundSmsLong %}
                        {{ country.outboundSmsLong }}
                    {% endif %}
                </p>
            {% endif %}
            {% if country.outboundCallEnabled %}
                <p>
                    {{ 'space.phone.details_7'|trans }} {{ country.outboundCallNumber }}
                </p>
            {% endif %}
            {% if country.outboundSmsEnabled or country.outboundCallEnabled %}

                <p>{{ 'space.phone.details_3'|trans }}</p>
                <br/>
            {% endif %}
        {% endif %}

        <p>{{ 'space.phone.details_4'|trans }} {{ 'space.phone.details_5'|trans }}</p>

    </div>

    <a href="{{ path('space_home', {sessionId: session.sessionId}) }}"
       class="btn btn-secondary">{{ 'base.button.back'|trans }}</a>

    <br/><br/>

{% endblock %}